version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: |
          git config credential.helper 'cache --timeout=120'
          git config --global user.email "hiasinho@me.com"
          git config --global user.name "Mathias Maisberger"
      - run: git add dist && git commit -m "Deploy"
      - run: git subtree push -q --prefix dist https://${GITHUB_PERSONAL_TOKEN}@github.com/strassentechnik/toolbox.git gh-pages
